#!/bin/sh

target=itooii-api-1.0-SNAPSHOT

if [ -f ${target}/itooii-api.pid ]; then
    kill `cat ${target}/itooii-api.pid`
fi
rm -rf $target
./activator clean dist
unzip target/universal/${target}.zip
itooii-api-1.0-SNAPSHOT/bin/itooii-api $* &
echo $! > ${target}/itooii-api.pid
